# Generated by Django 3.2.6 on 2021-09-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='phone',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
