# Generated by Django 3.2.6 on 2021-09-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_contactdetail_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
