# Generated by Django 3.2.6 on 2021-09-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_contactdetail_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonDiscountedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet/')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
                ('created_on', models.TimeField()),
            ],
        ),
    ]
