# Generated by Django 3.2.6 on 2021-09-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_amazondiscountedproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazondiscountedproducts',
            name='body',
        ),
        migrations.RemoveField(
            model_name='amazondiscountedproducts',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='amazondiscountedproducts',
            name='image',
        ),
        migrations.RemoveField(
            model_name='amazondiscountedproducts',
            name='title',
        ),
        migrations.AddField(
            model_name='amazondiscountedproducts',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
