# Generated by Django 3.2.6 on 2021-09-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210911_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecommerce', models.CharField(choices=[('AZ', 'Amazon'), ('FK', 'Flipkart'), ('SD', 'Snapdeal')], default='AZ', max_length=4)),
                ('image', models.ImageField(upload_to='card/')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AmazonDiscountedProducts',
        ),
    ]
