# Generated by Django 3.2.6 on 2021-09-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210911_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddata',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
