# Generated by Django 3.2.6 on 2021-09-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_carddata_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddata',
            name='created_on',
        ),
    ]
