# Generated by Django 3.2.6 on 2021-09-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_amazondata_ecommerce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazondata',
            name='created_on',
        ),
    ]
