# Generated by Django 3.2.6 on 2021-09-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_amazondata_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlipkartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='flipkart/card')),
            ],
        ),
        migrations.CreateModel(
            name='SnapdealData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='snapdeal/card')),
            ],
        ),
        migrations.AlterField(
            model_name='amazondata',
            name='image',
            field=models.ImageField(upload_to='amazon/card'),
        ),
    ]
