# Generated by Django 3.2.6 on 2021-09-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210911_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazondata',
            name='body',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='flipkartdata',
            name='body',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='snapdealdata',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
