# Generated by Django 3.2.6 on 2021-09-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210912_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazondata',
            name='url',
            field=models.CharField(default='https://www.amazon.in/', max_length=1000),
        ),
        migrations.AddField(
            model_name='flipkartdata',
            name='url',
            field=models.CharField(default='https://www.flipkart.com/', max_length=1000),
        ),
        migrations.AddField(
            model_name='snapdealdata',
            name='url',
            field=models.CharField(default='https://www.snapdeal.com/', max_length=1000),
        ),
    ]
