# Generated by Django 3.2.6 on 2021-09-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210912_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapdealdata',
            name='body',
            field=models.TextField(max_length=250),
        ),
    ]
