# Generated by Django 3.2.6 on 2021-09-12 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_snapdealdata_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazondata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 14, 47, 22, 632298, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='amazondata',
            name='created_time',
            field=models.TimeField(default=datetime.datetime(2021, 9, 12, 14, 47, 22, 632298, tzinfo=utc)),
        ),
    ]
