# Generated by Django 3.2.6 on 2021-09-12 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210912_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazondata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 14, 48, 37, 546143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='amazondata',
            name='created_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
