# Generated by Django 3.2.6 on 2021-09-12 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210912_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazondata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 20, 21, 44, 779080)),
        ),
        migrations.AlterField(
            model_name='amazondata',
            name='created_time',
            field=models.TimeField(default=datetime.datetime(2021, 9, 12, 14, 51, 44, 779080, tzinfo=utc)),
        ),
    ]
