# Generated by Django 3.2.6 on 2021-09-12 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20210912_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazondata',
            name='created_time',
        ),
        migrations.AlterField(
            model_name='amazondata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 20, 23, 19, 913071)),
        ),
    ]
