# Generated by Django 3.2.6 on 2021-09-12 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20210912_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazondata',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='flipkartdata',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='snapdealdata',
            name='created_date',
        ),
        migrations.AddField(
            model_name='amazondata',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 20, 26, 36, 112181)),
        ),
        migrations.AddField(
            model_name='flipkartdata',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 20, 26, 36, 112181)),
        ),
        migrations.AddField(
            model_name='snapdealdata',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 20, 26, 36, 112181)),
        ),
    ]
