# Generated by Django 3.2.6 on 2021-09-15 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20210912_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazondata',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 0, 35, 58, 187527)),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='phone',
            field=models.IntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='flipkartdata',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 0, 35, 58, 187527)),
        ),
        migrations.AlterField(
            model_name='snapdealdata',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 0, 35, 58, 187527)),
        ),
    ]
