# Generated by Django 3.2.6 on 2021-09-20 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20210920_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazondata',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 21, 30, 33, 991116)),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flipkartdata',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 21, 30, 33, 991116)),
        ),
        migrations.AlterField(
            model_name='snapdealdata',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 21, 30, 33, 991116)),
        ),
    ]
