# Generated by Django 3.2.6 on 2021-09-20 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20210920_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazondata',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 1, 24, 22, 742947)),
        ),
        migrations.AlterField(
            model_name='flipkartdata',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 1, 24, 22, 742947)),
        ),
        migrations.AlterField(
            model_name='snapdealdata',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 1, 24, 22, 742947)),
        ),
    ]
